import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import "./app.css";
import Header from "@/components/Header";

const alpino = localFont({
  src: "./fonts/Alpino-Variable.woff2",
  display: "swap",
  weight: "100 900",
  variable: "--font-alpino",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={alpino.variable}>
      {/* スクロールバーが表示されなくなる */}
      <body className="font-alpino overflow-hidden bg-green-400">
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
